version: "3"

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: 123456
      MYSQL_LOG_ERROR: /var/log/mysql/error.log
      MYSQL_GENERAL_LOG_FILE: /var/log/mysql/general.log
      MYSQL_SLOW_QUERY_LOG_FILE: /var/log/mysql/slow_query.log
      MYSQL_MAX_CONNECTIONS: 50
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    build: ./drupal
    volumes:
      - ./drupal:/var/www/html
    container_name: drupal
    depends_on:
      - mysql
    networks:
      - internal
      - external

  webserver:
    image: nginx:1.25.5-alpine
    container_name: webserver
    depends_on:
      - drupal
    ports:
      - "80:80"
    volumes:
      - ./drupal:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - external

  react-app:
    build: ./react-app/
    container_name: react
    volumes:
      - ./react-app:/app
    ports:
      - "5001:80"
    environment:
      - API_URL=http://webserver/api
    networks:
      - internal
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal:
  db-data:
